[project]
name = "textanalysis-cedanl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastexcel>=0.12.1",
    "pandas>=2.2.3",
    "polars>=1.20.0",
    "pyyaml>=6.0.2",
    "streamlit>=1.41.1",
]
