bar_chart_colors: viridis
max_topics_scale: 10
top_words_to_show: 30
filter_file_prefix: Topic_Modeling_analysis
initial_popup_text: |
  1) load an excel file (.xls or .xlsx)
  2) select a sheet and column
  3) run topic modeling or create a word cloud
  4) adjust topics or filter words as needed
  5) export your results

  tip: hover over labels for tooltips.
placeholder_sentiment_text: sentiment analysis not yet implemented
allowed_filetypes:
  - - Excel files
    - "*.xlsx;*.xls"
